version: '3.8'

services:
  votemonitorapi:
    image: votemonitorapi
    build:
      context: api
      dockerfile: src/Vote.Monitor.Api/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
        - REVISION=LocalBuild
    container_name: votemonitorapi
    env_file:
      - .env
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_started

  posgress_ui:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@code.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:  
      - "5050:80"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    container_name: postgresql-local
    volumes:
      - db-data:/var/lib/postgresql/data:rw,size=200m
      
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./.data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  hangfire:
    image: votemonitorhangfire
    build:
      context: api
      dockerfile: src/Vote.Monitor.Hangfire/Dockerfile
      args:
        - BUILD_CONFIGURATION=Development
        - REVISION=LocalBuild
    container_name: votemonitorhangfire
    env_file:
      - .env
    ports:
      - "5001:8080"
    depends_on:
      db:
        condition: service_started

  soketi:
    container_name: 'soketi_server'
    restart: unless-stopped
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    environment:
      - SOKETI_DEBUG='${DEBUG:-1}'
      - DEFAULT_APP_ID='${PUSHER_APP_ID:-some-id}'
      - DEFAULT_APP_KEY='${PUSHER_APP_KEY:-app-key}'
      - DEFAULT_APP_SECRET='${PUSHER_APP_SECRET:-some-app-secret}'
      - PUSHER_HOST='${PUSHER_HOST:-127.0.0.1}'
      - PUSHER_PORT= '${PUSHER_PORT:-6001}'
      - PUSHER_SCHEME='${PUSHER_SCHEME:-http}' # or https
      - METRICS_SERVER_PORT=${SOKETI_METRICS_SERVER_PORT:-9601}
      - SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES:-true}
    

volumes:
  db-data:
    driver: local




# docker-compose up -d
# docker-compose down
# docker-compose ps
# docker-compose logs
# docker inspect <containerid>  - inspect postgress to get the ip address , la mine ii 172.20.0.2
